services:
  app:
    build: .
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel_net
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=topes
      - DB_USERNAME=laraveluser
      - DB_PASSWORD=jD5v4YpXgTqsda

  mysql:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: topes
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: jD5v4YpXgTqsda
      MYSQL_ROOT_PASSWORD: yourpassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_net

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443" 
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/topes.mn/fullchain.pem:/etc/nginx/certs/topes.mn.crt:ro
      - /etc/letsencrypt/live/topes.mn/privkey.pem:/etc/nginx/certs/topes.mn.key:ro
    depends_on:
      - app
    networks:
      - laravel_net

networks:
  laravel_net:

volumes:
  mysql_data:
